apiVersion: cluster.x-k8s.io/v1alpha4
kind: ClusterClass
metadata:
  name: my-cluster-class
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
      kind: KubeadmControlPlaneTemplate
      name: my-cluster-class-control-plane
    machineInfrastructure:
      ref:
        kind: AWSMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        name: my-cluster-class-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
      kind: AWSClusterTemplate
      name: my-cluster-class-cluster
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            kind: KubeadmConfigTemplate
            apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
            name: my-cluster-class-md-0
        infrastructure:
          ref:
            kind: AWSMachineTemplate
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
            name: my-cluster-class-md-0
  variables:
    definitions:
    - name: region
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: us-east-1
    - name: sshKeyName
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: default
    - name: controlPlaneMachineType
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3.large
    - name: nodeMachineType
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: t3.large
  patches:
  - name: region
    definitions:
    - target:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSClusterTemplate
      jsonPatches:
      - op: replace
        path: “/spec/template/spec/region”
        valueFrom:
          variable: region
  - name: sshKeyName
    definitions:
    - target:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSClusterTemplate
      jsonPatches:
      - op: replace
        path: “/spec/template/spec/sshKeyName”
        valueFrom:
          variable: sshKeyName
    - target:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSMachineTemplate
      jsonPatches:
      - op: replace
        path: “/spec/template/spec/sshKeyName”
        valueFrom:
          variable: sshKeyName
  - name: controlPlaneMachineType
    definitions:
    - target:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSMachineTemplate
        selector:
          matchControlPlane: true
      jsonPatches:
      - op: replace
        path: “/spec/template/spec/instanceType”
        valueFrom:
          variable: controlPlaneMachineType
  - name: nodeMachineType
    definitions:
    - target:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AWSMachineTemplate
        selector:
          matchMachineDeployments:
          - default-worker
      jsonPatches:
      - op: replace
        path: “/spec/template/spec/instanceType”
        valueFrom:
          variable: nodeMachineType
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSClusterTemplate
metadata:
  name: my-cluster-class-cluster
spec:
  template:
    spec:
      region: REPLACEME
      sshKeyName: REPLACEME
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlaneTemplate
metadata:
  name: my-cluster-class-control-plane
spec:
  template:
    spec:
      machineTemplate:
        infrastructureRef:
          kind: AWSMachineTemplate
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
          name: "my-cluster-class-control-plane"
      kubeadmConfigSpec:
        initConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: aws
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: aws
          controllerManager:
            extraArgs:
              cloud-provider: aws
        joinConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: aws
      version: v1.22.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSMachineTemplate
metadata:
  name: my-cluster-class-control-plane
spec:
  template:
    spec:
      instanceType: REPLACEME
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: REPLACEME
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSMachineTemplate
metadata:
  name: my-cluster-class-md-0
spec:
  template:
    spec:
      instanceType: REPLACEME
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: REPLACEME
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: my-cluster-class-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
          kubeletExtraArgs:
            cloud-provider: aws
