apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  labels:
    cni: calico
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  topology:
    class: my-cluster-class
    version: v1.22.0
    controlPlane: {}
    variables:
    - name: clusterIdentityName
      value: ${CLUSTER_IDENTITY_NAME}
    - name: location
      value: ${AZURE_LOCATION}
    - name: vnetName
      value: ${AZURE_VNET_NAME:=${CLUSTER_NAME}-vnet}
    - name: resourceGroup
      value: ${AZURE_RESOURCE_GROUP:=${CLUSTER_NAME}}
    - name: subscriptionID
      value: ${AZURE_SUBSCRIPTION_ID}
    - name: sshPublicKeyB64
      value: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
    - name: controlPlaneMachineType
      value: ${AZURE_CONTROL_PLANE_MACHINE_TYPE}
    - name: nodeMachineType
      value: ${AZURE_NODE_MACHINE_TYPE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: ${CLUSTER_IDENTITY_NAME}
spec:
  allowedNamespaces: {}
  clientID: ${AZURE_CLIENT_ID}
  clientSecret:
    name: ${AZURE_CLUSTER_IDENTITY_SECRET_NAME}
    namespace: ${AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE}
  tenantID: ${AZURE_TENANT_ID}
  type: ServicePrincipal
