apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: my-cluster
spec:
  topology:
    class: my-cluster-class
    version: v1.22.0
    controlPlane: {}
    workers:
      machineDeployments:
      - class: default-worker
        name: default-worker
        replicas: 3
