apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: "my-cluster"
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.128.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: my-cluster-class
    version: v1.22.0
    controlPlane:
      metadata:
        labels:
          topologyLabel: topologyLabelValue
        annotations:
          topologyAnnotation: topologyAnnotation
      replicas: 1 # 1=>3=>1
    workers:
      machineDeployments:
        - class: default-worker
          name: default-worker-topology
          metadata:
            labels:
              topologyLabel: topologyLabelValue
            annotations:
              topologyAnnotation: topologyAnnotation
          replicas: 1 # 1=>3=>1
