apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: "my-cluster"
  namespace: default
spec:
  topology:
    class: my-cluster-class
    version: v1.22.0
    variables:
    - name: location
      value: us-east1
    - name: machineType
      value:
        cpu: 8
        gpu: 2
    - name: defaultObjectShouldNotOverwrite
      value:
        bar: clusterValue
